### ISSUE TITLE
Edge places the newly opened tab on top

### ISSUE THREAD

**Issue by Jkenwin** [UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox#10]
Hello, I would like to ask, Edge can put the newly opened tab on the top, and the button for the new tab on the top, how does this need to be implemented?

**Comment by UnlimitedAvailableUsername** [comment]
As far as I know, this can't be done natively through CSS. It requires JavaScript modification which isn't part of the Tree Style Tab Rules. So, no, it cannot be implemented.
