### ISSUE TITLE
Pinned tabs disappeared in Tree-Style-Tab

### ISSUE THREAD

**Issue by xtellaris** [UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox#15]
![image](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/40926741/b8adbd79-bef2-4d67-8bb1-ddfe2be5f72d)

Pinned tabs disappeared from the top of Tree-Stye-Tab, left 2 gap rows,  and I can't interact with pinned tabs.

## What did I tried

1. create a new profile from `about:profiles` and launch Firefox with it
2. install Tree-Style-Tab add-on
3. choose the "Proton" theme in Tree-Style-Tab setting
4. paste the content of `treestyletab-edge-mimicry.css` to *User Style Sheet* in Tree-Style-Tab setting
5. disable and re-enable the Tree-Style-Tab

> btw, I did not touch the userChrome mods or `about:config`.

## Version & Environment
- Firefox `123.0.1`
- Tree-Style-Tab `4.0.1`
- Windows 11 23H2

---

Anyway, Thanks for sharing your work, it does help me !  👍

**Comment by xtellaris** [comment]
![image](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/40926741/e8946d69-d4bb-4189-8997-2c3a30be232b)

I've tried treestyletab-edge-mimicry.css at commit [a5e2752](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/blob/a5e2752e617a895c01d21e1b9e38aff1fecdf227/treestyletab-edge-mimicry.css). 

It won't miss the pinned tab icon which could be interacted, but some favicons, like the one belongs to addon manager of Firefox in the image, are misplaced like issue #11

**Comment by UnlimitedAvailableUsername** [comment]
I am currently working on it. Tree Style Tab recently updated their HTML layout for the tab container.

**Comment by UnlimitedAvailableUsername** [comment]
Tree Style Tab has recently seperated the container for pinned tabs and normal tabs with id `pinned-tabs-container` and `normal-tabs-container`. For now, I've deleted some lines as it inteferes with the current layout speficially:

`#pinned-tabs-container {
 padding-top: 4px; 
}`

and

`:root.have-pinned-tabs #tabbar {
  margin-top: calc(var(--tabbar-margin-top) + 4px);
}`

I'll be updating the design soon, if possible within the day
