### ISSUE TITLE
Border through icon

### ISSUE THREAD

**Issue by AnmolMago** [UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox#5]
Thank you for making this theme!

 I get these lines across the fav-icon for version 108 on macOS and was hoping you could help fix them!

<img width="266" alt="Screenshot 2022-12-15 at 2 18 34 AM" src="https://user-images.githubusercontent.com/12145921/207797400-951de735-abf3-4b86-9357-218fafd5bef5.png">
<img width="264" alt="Screenshot 2022-12-15 at 2 18 43 AM" src="https://user-images.githubusercontent.com/12145921/207797412-d48b8991-84d5-409f-951a-d515393e1f3a.png">

**Comment by UnlimitedAvailableUsername** [comment]
I haven't tested this on MacOS since I don't own one. But I'm glad it's working well!

On your problem though, do you happen to have an extension installed called "TST Indent Line"? That might be the one causing those lines.

**Comment by AnmolMago** [comment]
Ahhh, you are right ... thank you!
