### ISSUE TITLE
Pin tabs visuals broke after the last firefox update (beta)

### ISSUE THREAD

**Issue by Minnona** [UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox#9]
FF version is 117.0b3

![image](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/23418072/51ac6bec-aa60-4d96-bb47-94a4e0232b5f)

**Comment by Minnona** [comment]
Now happens on stable v117 as well

**Comment by isahwn** [comment]
new BUG:

**Comment by isahwn** [comment]
new bug:
The + symbol will overlap with the New Tab character.
<img width="247" alt="image" src="https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/19422918/0f10c810-383f-4613-964e-95eaacd9526c">

**Comment by Minnona** [comment]
Pinning more than 1 tab puts the rest on the right side instead of putting them down
![image](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/23418072/dd48c630-f9a7-4759-9433-6c891ffbee96)
![image](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/23418072/39de421d-3f59-425a-98fe-0194d0c39bb0)

**Comment by UnlimitedAvailableUsername** [comment]
> new bug: The + symbol will overlap with the New Tab character. <img alt="image" width="247" src="https://user-images.githubusercontent.com/19422918/265145444-0f10c810-383f-4613-964e-95eaacd9526c.png">

my bad, I forgot about the two anchor buttons. Fixed it, try copying the new layout again

**Comment by UnlimitedAvailableUsername** [comment]
> Pinning more than 1 tab puts the rest on the right side instead of putting them down ![image](https://user-images.githubusercontent.com/23418072/265164407-dd48c630-f9a7-4759-9433-6c891ffbee96.png) ![image](https://user-images.githubusercontent.com/23418072/265164436-39de421d-3f59-425a-98fe-0194d0c39bb0.png) And there are some visual glitches when the sidebar opens/closes with pinned tabs, not sure how to describe it properly :p

That is a visual bug that I can't fix, see my list of important notes regarding that
